### ISSUE TITLE
Won't work for Windows10

### ISSUE THREAD

**Issue by deyt783** [ElKosto/PyCORe#1]
Hello! I was trying to do the simulations in Windows 10. But it won't work. Is there any way that the package works in Windows 10 also?

**Comment by ElKosto** [comment]
Hi deyt783,

The fast C++ part will not work on Windows at the current stage - it is built for Unix-based systems. 
However, the package on the main branch is tested for Windows 10. It requires only Python > 3.7 and corresponding packages. In this regard, Anaconda can be a good solution. 

Best regards
Alexey
